-- Criação das tabelas:

CREATE TABLE IF NOT EXISTS avaya (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    HORARIO_LOGIN TIME,
    HORARIO_LOGOUT TIME,
    HORARIO_PAUSA_1 TIME,
    HORARIO_PAUSA_2 TIME,
    DURACAO_LANCHE TIME,
    DIA_SEMANA INT,
    SUPERVISOR VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS bemoby (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    HORARIO_LOGIN TIME,
    HORARIO_LOGOUT TIME,
    HORARIO_PAUSA_1 TIME,
    HORARIO_PAUSA_2 TIME,
    DURACAO_LANCHE TIME,
    DIA_SEMANA INT,
    SUPERVISOR VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS escalas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_MATRICULA INT,
    NOME VARCHAR(100),
    HORARIO_ENTRADA TIME,
    HORARIO_SAIDA TIME,
    PAUSA_1 TIME,
    PAUSA_2 TIME,
    LANCHE TIME,
    DIA_SEMANA INT,
    SUPERVISOR VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS supervisores (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    AREA VARCHAR(100)
);
